version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - chess_database:/var/lib/postgresql/data
      - ./backend/dbshell:/docker-entrypoint-initdb.d/
    networks:
      - chess_net
  api:
    container_name: chess_api
    build: ./backend/.
    ports:
      - 8080:8080
    restart: always
    volumes:
      - api_volume:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - chess_net
  migrate:
    image: migrate/migrate:v4.15.2
    profiles: ["tools"]
    volumes:
      - ./backend/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable",
      ]
    command: ["up"]
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
  frontend:
    image: chess_frontend
    container_name: chess_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - chess_net
    ports:
      - 3000:80
    depends_on:
      - api

volumes:
  chess_database:
  api_volume:

networks:
  chess_net:
    driver: bridge
