version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: "${ENV}"
    image: chess-frontend
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true